application: symfony-glu
version: 1
runtime: php
api_version: 1

handlers:
- url: /bundles
  static_dir: web/bundles

- url: /favicon.ico
  static_files: web/favicon.ico
  upload: web/favicon.ico

- url: /.*
  script: web/app_dev.php